package com.example.acespringbackend.auth.dto;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class GoogleAuthResponse {
    private String token; // This might be a JWT generated by your backend for your app
    private String email;
    private String name; // Changed from 'name' to 'username' to align with User model
    private String imageUrl;
    private String provider;
}